export const menu = [
  {
    id: 1,
    image: "https://via.placeholder.com/150x100",
    title: "Smoke burger",
    description: "Tasty smoke burger",
    price: 7,
    quantity: 0,
  },
  {
    id: 2,
    image: "https://via.placeholder.com/150x100",
    title: "Vegan burger",
    description: "Vegan green burger",
    price: 6,
    quantity: 0,
  },
  {
    id: 3,
    image: "https://via.placeholder.com/150x100",
    title: "Lobster roll",
    description: "Rolling Lobster ROll",
    price: 10,
    quantity: 0,
  },
  {
    id: 4,
    image: "https://via.placeholder.com/150x100",
    title: "Sushi",
    description: "Awful sushi",
    price: 8,
    quantity: 0,
  },
  {
    id: 5,
    image: "https://via.placeholder.com/150x100",
    title: "Cheescake",
    description: "Berry cheescake",
    price: 3,
    quantity: 0,
  },
];
